const errors = {
  error: "There was an error!",
  firstNameRequired: "First name is required",
  lastNameRequired: "Last name is required",
  emailRequired: "Email is required",
  emailInvalid: "Email is invalid",
  emailExists: "Email already exists",
  emailNotExists: "No user found with that Email!",
  oldPasswordRequired: "Old password is required",
  samePassword: "Same password not allowed",
  passwordInvalid: "Password is incorrect!",
  passwordRequired: "Password is required",
  passwordMin: "Password must have at least 8 characters",
  passwordCombination:
    "Password must contain at least one special character and one number",
  secretRequired: "Secret is required",
  secretInvalid: "Invalid secret",
  roleRequired: "Role is required",
  roleOnly: "Role must be [user, admin]",
  tokenRequired: "Token is required",
  invalidToken: "Invalid or expired token",
  userNotFound: "User does not exist",
  userIdRequired: "User ID is required",
  userIdLength: "User ID should be 24 characters",
  userNameExists: "Username is not available!",
  imageRequired: "Image is required",
  pendingEmailVerification: "Email verification required",
  inactiveAccount: "Your account is not active! Kindly contact support!",
  alreadyVerified: "Account is already verified",
  notAuthorized: "Not authorized for this route!",
}

const texts = {
  allUsers: "All users",
  userData: "User data",
  userCreated: "User created",
  userUpdated: "User updated",
  userDeleted: "User deleted",
  passwordSuccess: "Password updated",
  loginSuccess: "User login successful",
  emailVerified: "Email verified successfully",
  passwordResetSent: "Password reset link sent",
  emailVerificationSent: "Email verfication link sent",
}

module.exports = {
  texts,
  errors,
  validations,
}
